### ISSUE TITLE
Inforgrafía

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Heidi-19#2]
Infografía gestión de proyectos de software

**Comment by Heidi-19** [comment]
[Infografia - Heidi Lucy Bautista Sanjuan 7USC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Heidi-19/files/12447156/Infografia.-.Heidi.Lucy.Bautista.Sanjuan.7USC.pdf)

**Comment by bg55-a** [comment]
calificacion:  20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
